### ISSUE TITLE
4월 26일 회의

### ISSUE THREAD

**Issue by joohongpark** [PPiing/wiki#1]

**Comment by jinbekim** [comment]
discusion은 어떤가요?

**Comment by jinbekim** [comment]
https://github.com/PPiing/PPoong/discussions

**Comment by jinbekim** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/59330110/165308933-057e2026-803d-4b6f-ac9e-b0e927af35f8.png">
목록에서 참여자 정보를 보여주지 않고  클릭을 했을때 참여자 정보를 불러오게 한다.는 의견

**Comment by jinbekim** [comment]
참여 여부는 왼쪽 목록에서 불러온 데이터 참조

**Comment by jinbekim** [comment]
초대하기 내일 고민하기
